language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install bundler
script: "script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false

cache: bundler
